---
application:
  build: .
  command: bundle exec ruby app.rb
  ports:
  - "4567:4567"
  links:
  - mariadb
  - redis
  environment:
    - RACK_ENV=production
mariadb:
  image: mariadb
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
redis:
  image: redis
