---
application:
  build: .
  command: bundle exec sidekiq -r ./workers/docker_job.rb -d; bundle exec ruby app.rb
  ports:
  - "4567:4567"
  links:
  - mariadb
  - redis
  environment:
    - RACK_ENV=production
    - REDIS_HOST=redis
    - REDIS_PORT=6379
mariadb:
  image: mariadb
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
redis:
  image: redis
