---
products:
  build: .
  command: bundle exec ruby app.rb
  ports:
  - "4567:4567"
  links:
  - mongodb
  - mongodb:mongodb.cloud66.local
  environment:
    - RAILS_ENV=production
    - RACK_ENV=production
mongodb:
  image: mongo
