---
application:
  build: .
  links:
  - postgres
  - redis
  environment:
    - RACK_ENV=production
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  env_file: .env
  command: bundle exec ruby app.rb
  ports:
  - "80:4567"
sidekiq:
  build: .
  links:
  - postgres
  - redis
  environment:
    - RACK_ENV=production
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  env_file: .env
  command: bundle exec sidekiq -r ./app.rb
postgres:
  image: postgres
redis:
  image: redis
