default: &default
  adapter: 'postgresql'
  encoding: unicode
  pool: <%= ENV.fetch("PG_POOL", 32) %>
production:
  <<: *default
  username: <%= ENV.fetch("POSTGRES_USER", 'postgres') %>
  host: <%= ENV.fetch("DATABASE_URL", 'postgres') %>
  database: 'docker_job_prod'
development:
  <<: *default
  database: 'docker_job_dev'
test:
  <<: *default
  database: 'docker_job_test'
