default: &default
  adapter: 'mysql2'
  host: 'localhost'
  username: 'root'
  password: ''
production:
  <<: *default
  database: 'docker_job_prod'
development:
  <<: *default
  database: 'docker_job_dev'
