default: &default
  adapter: 'mysql2'
  host: <%= ENV.fetch("DATABASE_URL", 'mariadb') %>
  username: 'root'
  password: ''
production:
  <<: *default
  database: 'docker_job_prod'
development:
  <<: *default
  database: 'docker_job_dev'
  host: 'localhost'
